---
- name: longhorn | check localhost kubeconfig
  ansible.builtin.stat:
    path: "{{ kubeconfig }}"
  register: kubeconfig_stat

- name: longhorn | assert localhost kubeconfig exists
  ansible.builtin.assert:
    that:
      - kubeconfig_stat.stat.exists
    fail_msg: "Local kubeconfig is required at {{ kubeconfig }}."
    quiet: true

- ansible.builtin.import_tasks: node-labels.yaml
- ansible.builtin.import_tasks: longhorn.yaml
- ansible.builtin.import_tasks: storageclasses.yaml
