---
- name: cilium | check localhost kubeconfig
  ansible.builtin.stat:
    path: "{{ kubeconfig }}"
  register: kubeconfig_stat

- name: cilium | assert localhost kubeconfig exists
  ansible.builtin.assert:
    that:
      - kubeconfig_stat.stat.exists
    fail_msg: "Local kubeconfig is required at {{ kubeconfig }}."
    quiet: true

- ansible.builtin.import_tasks: gateway-api.yaml
- ansible.builtin.import_tasks: cilium.yaml
- ansible.builtin.import_tasks: cilium-lb-ip-pool.yaml
- ansible.builtin.import_tasks: cilium-l2-policy.yaml
