apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system

  values:
    provider:
      name: rfc2136

    sources:
      - gateway-httproute

    domainFilters:
      - k8s.home.arpa

    policy: upsert-only # ToDo: set sync
    registry: txt
    txtOwnerId: k8s
#    txtPrefix: _extdns. ToDo: check created records
    triggerLoopOnEvent: true

    env:
      - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
        valueFrom:
          secretKeyRef:
            name: external-dns-k8s-home-arpa-tsig
            key: EXTERNAL_DNS_RFC2136_TSIG_SECRET

    extraArgs:
      - --rfc2136-host=technitium.home.arpa
      - --rfc2136-port=53
      - --rfc2136-zone=k8s.home.arpa
      - --rfc2136-tsig-keyname=externaldns-k8s-home-arpa
      - --rfc2136-tsig-secret-alg=hmac-sha256
