apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system

  values:
    provider:
      name: pihole

    sources:
      - gateway-httproute

    domainFilters:
      - k8s.home.arpa

    policy: upsert-only
    # Pi-hole provider in external-dns does not support TXT ownership tracking.
    registry: noop
    triggerLoopOnEvent: true

    env:
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: http://pihole.home.arpa
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: external-dns-pihole
            key: EXTERNAL_DNS_PIHOLE_PASSWORD

    extraArgs:
      - --pihole-api-version=6
