---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-network
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  description: Platform network components
  sourceRepos:
    - https://github.com/dsuprunov/homelab.git
    - https://github.com/kubernetes-sigs/gateway-api.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
