---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  description: Platform monitoring components
  sourceRepos:
    - https://github.com/dsuprunov/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
