---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: root-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: Argo CD root project
  sourceRepos:
    - https://github.com/dsuprunov/homelab.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: AppProject
