---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
  namespace: cilium-gateway
spec:
  listeners:
    - name: https-grafana
      hostname: grafana.k8s.home.arpa
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: grafana-tls
            kind: Secret
            group: ""
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              gateway.home.arpa/public: "true"
