---
- name: cert-manager | apply selfsigned cluster issuer
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('ansible.builtin.file', role_path ~ '/files/selfsigned-cluster-issuer.yaml') | from_yaml }}"

- name: cert-manager | wait for selfsigned cluster issuer
  ansible.builtin.command: >
    kubectl wait --for=condition=Ready --timeout=5m
      clusterissuer/selfsigned
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  retries: 3
  delay: 10
  register: cert_manager_selfsigned_cluster_issuer_ready
  until: cert_manager_selfsigned_cluster_issuer_ready.rc == 0
  changed_when: false
