apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-server
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  secretName: grafana-server-tls
  commonName: grafana.k8s.home.arpa
  subject:
    organizations:
      - homelab
    organizationalUnits:
      - monitoring
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h
  renewBefore: 360h
  usages:
    - digital signature
    - server auth
  dnsNames:
    - grafana.k8s.home.arpa
  issuerRef:
    name: monitoring-ca
    kind: Issuer
    group: cert-manager.io

