apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app: demo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      containers:
        - name: demo-app

          image: dsuprunov/demo-app
          imagePullPolicy: Always

          env:
            - name: DEMO_ENV_SECRET_LOGIN
              valueFrom:
                secretKeyRef:
                  name: demo-env-secret
                  key: DEMO_ENV_SECRET_LOGIN
            - name: DEMO_ENV_SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-env-secret
                  key: DEMO_ENV_SECRET_PASSWORD

          volumeMounts:
            - name: demo-file-secret
              mountPath: /var/run/secrets/demo-app/demo-file-secret
              readOnly: true

          securityContext:
            allowPrivilegeEscalation: false

          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 20m
              memory: 32Mi

          readinessProbe:
            exec:
              command: ["bash", "-c", "kill -0 1"]
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3

          livenessProbe:
            exec:
              command: ["bash", "-c", "kill -0 1"]
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3

      volumes:
        - name: demo-file-secret
          secret:
            secretName: demo-file-secret
