[vms]
vm-k8s-control-01 ansible_host=192.168.178.226 ansible_user=ubuntu
vm-k8s-control-02 ansible_host=192.168.178.227 ansible_user=ubuntu
vm-k8s-control-03 ansible_host=192.168.178.228 ansible_user=ubuntu
vm-k8s-worker-01  ansible_host=192.168.178.230 ansible_user=ubuntu
vm-k8s-worker-02  ansible_host=192.168.178.231 ansible_user=ubuntu
vm-k8s-worker-03  ansible_host=192.168.178.232 ansible_user=ubuntu

[k8s_node_base]
vm-k8s-control-01
vm-k8s-control-02
vm-k8s-control-03
vm-k8s-worker-01
vm-k8s-worker-02
vm-k8s-worker-03

[k8s_node_control]
vm-k8s-control-01
vm-k8s-control-02
vm-k8s-control-03

[k8s_cluster_init]
vm-k8s-control-01

[k8s_addon_cilium]
localhost ansible_connection=local

[k8s_node_control_join]
vm-k8s-control-02
vm-k8s-control-03

[k8s_node_worker]
vm-k8s-worker-01
vm-k8s-worker-02
vm-k8s-worker-03

[k8s_node_worker_join]
vm-k8s-worker-01
vm-k8s-worker-02
vm-k8s-worker-03

[k8s_addon_flux]
localhost ansible_connection=local
