[vms]
vm-coredns        ansible_host=192.168.178.206 ansible_user=debian
; vm-vault-01       ansible_host=192.168.178.208 ansible_user=debian
vm-k8s-control-01 ansible_host=192.168.178.231 ansible_user=ubuntu
; vm-k8s-control-02 ansible_host=192.168.178.232 ansible_user=ubuntu
; vm-k8s-control-03 ansible_host=192.168.178.233 ansible_user=ubuntu
vm-k8s-worker-01  ansible_host=192.168.178.236 ansible_user=ubuntu
vm-k8s-worker-02  ansible_host=192.168.178.237 ansible_user=ubuntu
vm-k8s-worker-03  ansible_host=192.168.178.238 ansible_user=ubuntu

[dns]
vm-coredns

; [vault]
; vm-vault-01

[k8s_node_base]
vm-k8s-control-01
; vm-k8s-control-02
; vm-k8s-control-03
vm-k8s-worker-01
vm-k8s-worker-02
vm-k8s-worker-03

[k8s_node_control]
vm-k8s-control-01
; vm-k8s-control-02
; vm-k8s-control-03

[k8s_cluster_init]
vm-k8s-control-01

[k8s_addon_cilium]
localhost ansible_connection=local

; [k8s_node_control_join]
; vm-k8s-control-02
; vm-k8s-control-03

[k8s_node_worker]
vm-k8s-worker-01
vm-k8s-worker-02
vm-k8s-worker-03

[k8s_node_worker_join]
vm-k8s-worker-01
vm-k8s-worker-02
vm-k8s-worker-03

[k8s_node_longhorn]
vm-k8s-worker-01
vm-k8s-worker-02
vm-k8s-worker-03

[k8s_addon_kubelet_csr_approver]
localhost ansible_connection=local

[k8s_addon_cert_manager]
localhost ansible_connection=local

[k8s_addon_metrics_server]
localhost ansible_connection=local

[k8s_addon_node_local_dns]
localhost ansible_connection=local

[k8s_addon_longhorn]
localhost ansible_connection=local

[k8s_addon_kube_prometheus_stack]
localhost ansible_connection=local

[k8s_addon_flux]
; localhost ansible_connection=local
