---
- name: kube-prometheus-stack | apply namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('ansible.builtin.file', role_path ~ '/files/namespace.yaml') | from_yaml }}"

