---
- name: kubeconfig
  block:
    - name: kubeconfig | check if admin kubeconfig exists on init node
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: admin_conf

    - name: kubeconfig | sync local kubeconfig
      when: admin_conf.stat.exists
      block:
        - name: kubeconfig | ensure local .kube dir exists
          delegate_to: localhost
          become: false
          ansible.builtin.file:
            path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube"
            state: directory
            mode: "0700"

        - name: kubeconfig | fetch admin kubeconfig to local home
          become: true
          ansible.builtin.fetch:
            src: /etc/kubernetes/admin.conf
            dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config"
            flat: true

        - name: kubeconfig | set local kubeconfig permissions
          delegate_to: localhost
          become: false
          ansible.builtin.file:
            path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.kube/config"
            mode: "0600"
