---
- name: kube-prometheus-stack | install
  kubernetes.core.helm:
    release_name: kube-prometheus-stack
    chart_ref: kube-prometheus-stack
    chart_repo_url: "{{ kube_prometheus_stack_chart_repo_url }}"
    chart_version: "{{ kube_prometheus_stack_version }}"
    release_namespace: monitoring
    create_namespace: false
    release_values: "{{ lookup('ansible.builtin.file', role_path ~ '/files/values.yaml') | from_yaml }}"
    kubeconfig: "{{ kubeconfig }}"
    wait: true
    timeout: 15m
    state: present
  retries: 6
  delay: 30
  register: kube_prometheus_stack_deploy
  until: kube_prometheus_stack_deploy is succeeded

- name: kube-prometheus-stack | wait for pods
  ansible.builtin.command: >
    kubectl wait --for=condition=Ready pod --all
      -n monitoring
      --timeout=15m
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  retries: 3
  delay: 10
  register: kube_prometheus_stack_pods_ready
  until: kube_prometheus_stack_pods_ready.rc == 0
  changed_when: false

