apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-website-namespace
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/apps/demo-website/namespace
  prune: true
  timeout: 5m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-website
  namespace: flux-system
spec:
  dependsOn:
    - name: demo-website-namespace
  interval: 10m
  path: ./flux/apps/demo-website/kustomize
  prune: true
  timeout: 5m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-website-ingress
  namespace: flux-system
spec:
  dependsOn:
    - name: demo-website
  interval: 10m
  path: ./flux/apps/demo-website/ingress
  prune: true
  timeout: 5m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
