---
defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn

  defaultReplicaCount: 1

  storageReservedPercentageForDefaultDisk: 0
  storageMinimalAvailablePercentage: 10

persistence:
  defaultClassReplicaCount: 1
