---
- name: k8s | preflight
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: preflight | check kubectl
      ansible.builtin.command: kubectl version --client
      changed_when: false

    - name: preflight | check helm
      ansible.builtin.command: helm version
      changed_when: false

- name: k8s | node
  hosts: k8s_node_base
  become: true
  gather_facts: true
  roles:
    - k8s_node_base

- name: k8s | control
  hosts: k8s_node_control
  become: true
  gather_facts: true
  roles:
    - k8s_node_control

- name: k8s | cluster init
  hosts: k8s_cluster_init
  become: true
  gather_facts: true
  roles:
    - k8s_cluster_init

- name: k8s | cilium
  hosts: k8s_addon_cilium
  connection: local
  gather_facts: false
  tags:
    - cilium
  roles:
    - k8s_addon_cilium

- name: k8s | control join
  hosts: k8s_node_control_join
  become: true
  gather_facts: true
  roles:
    - k8s_node_control_join

- name: k8s | worker
  hosts: k8s_node_worker
  become: true
  gather_facts: true
  roles:
    - k8s_node_worker

- name: k8s | worker join
  hosts: k8s_node_worker_join
  become: true
  gather_facts: true
  roles:
    - k8s_node_worker_join

- name: k8s | flux
  hosts: k8s_addon_flux
  become: true
  gather_facts: true
  tags:
    - flux
  roles:
    - role: k8s_addon_flux
