---
- name: longhorn | preflight
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: preflight | check kubectl
      ansible.builtin.command: kubectl version --client
      changed_when: false

    - name: preflight | check helm
      ansible.builtin.command: helm version
      changed_when: false

- name: longhorn | node
  hosts: k8s_node_longhorn
  become: true
  gather_facts: true
  roles:
    - k8s_node_longhorn

- name: longhorn | install
  hosts: k8s_addon_longhorn
  connection: local
  gather_facts: false
  roles:
    - k8s_addon_longhorn
