---
prometheus:
  prometheusSpec:
    externalLabels:
      cluster: homelab

grafana:
  enabled: true
  fullnameOverride: grafana
  defaultDashboardsEnabled: false

  service:
    type: ClusterIP
    port: 443
    targetPort: 3000
    appProtocol: https

  ingress:
    enabled: false

  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
      scheme: HTTPS

  livenessProbe:
    httpGet:
      path: /api/health
      port: 3000
      scheme: HTTPS

  extraSecretMounts:
    - name: grafana-server-tls
      secretName: grafana-server-tls
      mountPath: /etc/grafana/tls
      defaultMode: 0440
      readOnly: true

  sidecar:
    dashboards:
      enabled: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: true
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      k8s-system-api-server:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-api-server.json
        datasource: Prometheus
      k8s-system-coredns:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-system-coredns.json
        datasource: Prometheus
      k8s-views-global:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-global.json
        datasource: Prometheus
      k8s-views-namespaces:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-namespaces.json
        datasource: Prometheus
      k8s-views-nodes:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-nodes.json
        datasource: Prometheus
      k8s-views-pods:
        url: https://raw.githubusercontent.com/dotdc/grafana-dashboards-kubernetes/master/dashboards/k8s-views-pods.json
        datasource: Prometheus

  grafana.ini:
    server:
      protocol: https
      domain: grafana.k8s.home.arpa
      root_url: https://grafana.k8s.home.arpa
      cert_file: /etc/grafana/tls/tls.crt
      cert_key: /etc/grafana/tls/tls.key
    auth.anonymous:
      enabled: true
      org_role: Admin
    auth:
      disable_login_form: true

