---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-argocd
  source:
    repoURL: https://github.com/dsuprunov/homelab.git
    targetRevision: HEAD
    path: argocd/workloads/argocd
    helm:
      releaseName: argocd
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        gateway.home.arpa/public: "true"
    syncOptions:
      - CreateNamespace=true
