---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-monitoring
  source:
    repoURL: https://github.com/dsuprunov/homelab.git
    targetRevision: HEAD
    path: argocd/workloads/kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
        - values.yaml
        - values-dashboards.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        gateway.home.arpa/public: "true"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
