---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-system
  source:
    repoURL: https://github.com/dsuprunov/homelab.git
    targetRevision: HEAD
    path: argocd/workloads/metrics-server
    helm:
      releaseName: metrics-server
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
