---
- name: flux
  block:
    - name: flux | check localhost kubeconfig
      ansible.builtin.stat:
        path: "{{ kubeconfig }}"
      register: flux_kubeconfig_stat

    - name: flux | assert localhost kubeconfig exists
      ansible.builtin.assert:
        quiet: true
        that:
          - flux_kubeconfig_stat.stat.exists
        fail_msg: "Local kubeconfig is required at {{ kubeconfig }}."

    - name: flux | check flux cli
      ansible.builtin.command: flux --version
      changed_when: false
      run_once: true

    - name: flux | validate GitHub token
      vars:
        github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') | trim }}"
      ansible.builtin.uri:
        url: https://api.github.com/user
        headers:
          Authorization: "Bearer {{ github_token }}"
          Accept: "application/vnd.github+json"
          X-GitHub-Api-Version: "2022-11-28"
      register: token_check
      changed_when: false
      run_once: true
      no_log: true

    - name: flux | token OK
      when: token_check.status == 200
      block:
        - name: flux | pre-check
          ansible.builtin.command: flux check --pre
          environment:
            KUBECONFIG: "{{ kubeconfig }}"
          register: flux_precheck_result
          changed_when: false
          run_once: true

        - name: flux | pre-check OK
          when: flux_precheck_result.rc == 0
          block:
            - name: flux | bootstrap
              vars:
                github_token: "{{ lookup('ansible.builtin.env', 'GITHUB_TOKEN') | trim }}"
              ansible.builtin.command: >
                flux bootstrap github
                  --owner=dsuprunov
                  --repository=homelab
                  --branch=main
                  --path=flux
                  --personal
                  --reconcile=true
                  --token-auth=false
              environment:
                GITHUB_TOKEN: "{{ github_token }}"
                KUBECONFIG: "{{ kubeconfig }}"
              register: flux_bootstrap_result
              changed_when: >
                ('committed'  in flux_bootstrap_result.stderr) or
                ('installed'  in flux_bootstrap_result.stderr) or
                ('configured' in flux_bootstrap_result.stderr)
              run_once: true
              # ToDo: wait, timeout, state ...
