---
- name: node-local-dns | check localhost kubeconfig
  ansible.builtin.stat:
    path: "{{ kubeconfig }}"
  register: kubeconfig_stat

- name: node-local-dns | assert localhost kubeconfig exists
  ansible.builtin.assert:
    that:
      - kubeconfig_stat.stat.exists
    fail_msg: "Local kubeconfig is required at {{ kubeconfig }}."
    quiet: true

- ansible.builtin.import_tasks: node-local-dns.yaml
- ansible.builtin.import_tasks: node-local-dns-lrp.yaml
