apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: demo-hashicorp-vso
  namespace: demo-hashicorp-vso
spec:
  address: https://vault.home.arpa:8200
  tlsServerName: vault.home.arpa
  caCertSecretRef: vault-home-arpa-ca
