apiVersion: v1
kind: Secret
metadata:
  name: vault-home-arpa-ca
  namespace: demo-hashicorp-vso
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFMTCCAxmgAwIBAgIUU3hAmR7nx/w9MnpwItMj6tULnp0wDQYJKoZIhvcNAQEL
    BQAwGjEYMBYGA1UEAwwPdmF1bHQuaG9tZS5hcnBhMB4XDTI2MDUxMDEyMzAyNFoX
    DTM2MDUwNzEyMzAyNFowGjEYMBYGA1UEAwwPdmF1bHQuaG9tZS5hcnBhMIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEApm4dozZBDbZvSPIiAQHp7QYJ7ROW
    AzxeV7mJyVFd/p2gUvmY2Smw6aiYT3Knq+b2IIyCpjyitM2XHUgmF80c6JGYXQ9h
    o5JGR4xUyBjaz35U7iSLd8sByzgR+to4WcqhoxKKs5r5jb4bWZE8jCm4GXZcsUS/
    ZdmST1GRyvR0hGV+R/nlD6rFYAjGQeOIfuo/uSzMjy/zuD/Zm7BhyORxqMISnpPJ
    c7VuY/waMaCXmZ9Ly5r7Tlezuy3uIg4R917PBcL5+yg1fJjIVJa9aJRMmdHqLAQh
    23qWb2E2Sv6bYSiVZMDw018f8x9JgyepQin3rWmIrrrLstZwpr9Zv91W9lEsxGXk
    vTxCGDfpybO67LBkvHiZYyPDO44pXc+6FBZ8hRhfwwn3A1GFJXVqNyCrRM8Cb+RU
    tfBtn6eLA8VVnKoJJ4na+87O6jJxvV8GAF7oGUrLCV7eSqCoF2gVr6y2jXDJbzRC
    JWjGAWe2DkZmeLi3YqzBlTbTuIBA9kPIv1o7Ioa8z4LsHxcg2kNpPzMBmhImxAfg
    5k/Xf5mbTKRkkaZTfSfqNvy2m35YNEHBWLzTEp0JoXT5P37H/JQA/T5sYhQycLXB
    u8Eh4GdKbaX5o9S4hUHCZyGPZafdTUl50ZDEqglNVy5yZNA4gKRmbCt4e26pOoJc
    3oPvmwO6azk8YCsCAwEAAaNvMG0wHQYDVR0OBBYEFDRFwutD1Pwt0x4N7yXvUO6F
    Fw5DMB8GA1UdIwQYMBaAFDRFwutD1Pwt0x4N7yXvUO6FFw5DMA8GA1UdEwEB/wQF
    MAMBAf8wGgYDVR0RBBMwEYIPdmF1bHQuaG9tZS5hcnBhMA0GCSqGSIb3DQEBCwUA
    A4ICAQBqHmGgnXj2ta9aBmmonXOmCBkB1eUF5ypHIRiPRaJ9iHMhm+DD435Bvcpn
    NwqzaumgoskCcBUiluJ1MKgmg4udivcH9c144erzqj8x509N2JhYFyKr1sDfQLF9
    96R+x7bPAH3qFfyxyYedrtXlPyX7GIEErdsEhDJGRADqJ+ZTZqvZt61VQSsLzQNk
    zdB6ew6ElLxLpp2IpezFf3KrmYQNNJ0MEmtS4QpyAem7SOrQrNaHf1W+fDhL+rbT
    MZDkSti/sp/G6sr0mvfr7Zaujoo+akKBncLurW9pKH/v039bLej0yrnNyxjvfCbt
    mrJ9hbF2QAsKoqEpHaJUEy279WN+dm44mlAu2YVAmA71IVbqt9SsawRwVXRsjkDR
    5wGZGOM/JZ+pCxOjNXxSZQMigKmkgvCu8f6b8cZVhBAADQN9Ny9dKO5/WfDaqG0R
    AlGipvQvUhEecGzkS/IS+KzuDeU4wR0sc4ZktTuSBz24Ld5mLY3Z0alb02Te2yVU
    x9+goqHZmfbGfMCXy+dP88Bb23SihisAe2xXDgYHnA7S9VypdZ8oaANJQA7jZvWt
    YbwYaJovwzfL8gld7KcVSRAohRiBYcnJf8StqujbPV6MDb9aT65NdA+vqlHjYYqY
    qqZVnbq5Zopr8eu9GWO7AB5nUk5meJzWbrZXbVtu3bSu0syz1A==
    -----END CERTIFICATE-----
