apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: demo-hashicorp-vso-env
  namespace: demo-hashicorp-vso
spec:
  vaultAuthRef: demo-hashicorp-vso
  mount: secret
  type: kv-v2
  path: demo-hashicorp-vso/env
  refreshAfter: 1m
  hmacSecretData: true
  destination:
    create: true
    overwrite: true
    name: demo-hashicorp-vso-env-secret
