apiVersion: v1
kind: Pod
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  hostNetwork: true
  hostAliases:
    - ip: 127.0.0.1
      hostnames:
        - kubernetes
  containers:
    - name: kube-vip
      image: ghcr.io/kube-vip/kube-vip:v1.0.4
      imagePullPolicy: Always
      args:
        - manager
      env:
        - name: vip_arp
          value: "true"
        - name: port
          value: "6443"
        - name: vip_interface
          value: "eth0"
        - name: vip_subnet
          value: "32"
        - name: cp_enable
          value: "true"
        - name: cp_namespace
          value: "kube-system"
        - name: vip_ddns
          value: "false"
        - name: svc_enable
          value: "false"
        - name: vip_leaderelection
          value: "true"
        - name: vip_leaseduration
          value: "5"
        - name: vip_renewdeadline
          value: "3"
        - name: vip_retryperiod
          value: "1"
        - name: address
          value: "10.10.0.120"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
            - SYS_TIME
      volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubernetes/admin.conf
  volumes:
    - name: kubeconfig
      hostPath:
        path: /etc/kubernetes/admin.conf
