apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: metrics-server
      version: "3.13.0"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
